/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package blend.buddyapp.api.resources.token.controller;


import blend.buddyapp.api.resources.token.models.LoginRequestBody;
import io.swagger.annotations.*;
import org.keycloak.representations.AccessTokenResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-09-14T03:02:35.640+02:00[Europe/Prague]")
@io.swagger.annotations.Api(value = "auth", description = "the auth API")
public interface TokenApi {
    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }
    @ApiOperation(value = "Log in a registered user, get a token in return", nickname = "login", notes = "", response = AccessTokenResponse.class, tags={ "auth", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "login succesfull", response = AccessTokenResponse.class),
            @ApiResponse(code = 401, message = "wrong username or password") })
    @RequestMapping(value = "/token",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    default ResponseEntity<?> login(@ApiParam(value = "password and student number" ,required=true )  @Valid @RequestBody LoginRequestBody loginRequestBody) {
        return new ResponseEntity<AccessTokenResponse>(HttpStatus.NOT_IMPLEMENTED);
    }
}
